### ISSUE TITLE
Translating `ofScientific`

### ISSUE THREAD

**Issue by yangky11** [yangky11/lean-smt#2]
```lean
theorem exercise_10_4 : ∀ (a b c : ℝ), a > 0 ∧ b > 0 ∧ c > 0 → (a + 2 * b + 3 * c)^2 / (a^2 + 2 * b^2 + 3 * c^2) ≤ 5.5 := by
  intro a b c
  smt!
```
![image](https://github.com/yangky11/lean-smt/assets/5431913/1f030364-9033-4922-88d3-69afca2938ab)

**Comment by JC-Chen1** [comment]
Just created a pull request to support Rat.ofScientific on https://github.com/yangky11/lean-smt/pull/6.

Specifically, I added some operations to handle the Scientific calculation and now 5.5 will be translated automatically as below,

```
(div 55 (^ 10 1))
```

Now it should work smoothly.

**Comment by yangky11** [comment]
Thx!
